---
- name: Apt cleanup ({{ ansible_os_family }})
  become: "{{ (ansible_user_id is defined and ansible_user_id != 'root') or (lookup('env', 'UID') | int != 0) }}"
  block:
    - name: Removes dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
        purge: true
    - name: Cleans Apt cache
      ansible.builtin.apt:
        autoclean: true
        clean: true
